### ISSUE TITLE
Update Translations

### ISSUE THREAD

**Issue by benwilhelm** [open-city/kcbx-petcoke#26]
Hey @renemarcelo, can you take a look at the updated site on the "develop" branch and give us some updated translations?

**Comment by renemarcelo** [comment]
Pending a final look, translations are on my m branch.
-R

On March 9, 2016, at 9:22 PM, Ben notifications@github.com wrote:

Hey @renemarcelo, can you take a look at the updated site on the "develop" branch and give us some updated translations?

**Comment by benwilhelm** [comment]
Thanks @renemarcelo
